project_id = "vcpohetbsyyjqqkzuzxj"

[functions.rent-reminders]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.twilio-notifications]
verify_jwt = false

[functions.send-sms-otp]
enabled = true
verify_jwt = false
import_map = "./functions/send-sms-otp/deno.json"
entrypoint = "./functions/send-sms-otp/index.ts"
