import { useRef } from "react";
import { format } from "date-fns";
import { FileText, IndianRupee, Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ReceiptProps {
  payment: {
    id: string;
    amount: number;
    month: string;
    payment_date: string | null;
    status: string;
    properties?: { name: string } | null;
    rooms?: { room_number: string } | null;
  };
  tenantName?: string;
}

const RentReceipt = ({ payment, tenantName }: ReceiptProps) => {
  const receiptRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    const content = receiptRef.current;
    if (!content) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Rent Receipt - ${payment.month}</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 40px; max-width: 600px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 2px solid #7c3aed; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { color: #7c3aed; margin: 0; font-size: 24px; }
        .header p { color: #666; margin: 4px 0 0; }
        .details { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 24px; }
        .detail-item label { display: block; font-size: 12px; color: #888; text-transform: uppercase; }
        .detail-item p { margin: 2px 0 0; font-weight: 600; font-size: 15px; }
        .amount-box { background: #f5f3ff; border: 1px solid #ddd6fe; border-radius: 8px; padding: 16px; text-align: center; margin-bottom: 24px; }
        .amount-box .amt { font-size: 28px; font-weight: 700; color: #7c3aed; }
        .footer { text-align: center; color: #888; font-size: 12px; border-top: 1px solid #eee; padding-top: 16px; }
        @media print { body { padding: 20px; } }
      </style></head><body>
      <div class="header">
        <h1>🏠 PG Buddy</h1>
        <p>Rent Payment Receipt</p>
      </div>
      <div class="details">
        <div class="detail-item"><label>Receipt No</label><p>${payment.id.slice(0, 8).toUpperCase()}</p></div>
        <div class="detail-item"><label>Date</label><p>${payment.payment_date ? format(new Date(payment.payment_date), "dd MMM yyyy") : format(new Date(), "dd MMM yyyy")}</p></div>
        <div class="detail-item"><label>Property</label><p>${payment.properties?.name || "—"}</p></div>
        <div class="detail-item"><label>Room</label><p>${payment.rooms?.room_number || "—"}</p></div>
        <div class="detail-item"><label>Tenant</label><p>${tenantName || "—"}</p></div>
        <div class="detail-item"><label>Month</label><p>${payment.month}</p></div>
      </div>
      <div class="amount-box">
        <div style="font-size:12px;color:#888;">Amount Paid</div>
        <div class="amt">₹${Number(payment.amount).toLocaleString()}</div>
      </div>
      <div class="details">
        <div class="detail-item"><label>Status</label><p style="color:#16a34a;">✓ ${payment.status.toUpperCase()}</p></div>
      </div>
      <div class="footer">
        <p>This is a computer-generated receipt and does not require a signature.</p>
        <p>Generated by PG Buddy</p>
      </div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  if (payment.status !== "paid") return null;

  return (
    <Button variant="ghost" size="sm" className="gap-1.5 text-xs" onClick={handlePrint}>
      <FileText className="w-3 h-3" />
      Receipt
    </Button>
  );
};

export default RentReceipt;
