-- Full Database Reset
-- Permanently deletes ALL data from public schema tables

TRUNCATE TABLE public.profiles CASCADE;
TRUNCATE TABLE public.user_roles CASCADE;
TRUNCATE TABLE public.properties CASCADE;
TRUNCATE TABLE public.rooms CASCADE;
TRUNCATE TABLE public.beds CASCADE;
TRUNCATE TABLE public.tenant_assignments CASCADE;
TRUNCATE TABLE public.tenant_invitations CASCADE;
TRUNCATE TABLE public.rent_payments CASCADE;
TRUNCATE TABLE public.utility_bills CASCADE;
TRUNCATE TABLE public.complaints CASCADE;
TRUNCATE TABLE public.community_messages CASCADE;
TRUNCATE TABLE public.visitor_logs CASCADE;
TRUNCATE TABLE public.announcements CASCADE;
TRUNCATE TABLE public.vacancy_notices CASCADE;
TRUNCATE TABLE public.expenses CASCADE;
TRUNCATE TABLE public.audit_logs CASCADE;
TRUNCATE TABLE public.staff_members CASCADE;
TRUNCATE TABLE public.subscriptions CASCADE;
TRUNCATE TABLE public.referrals CASCADE;
TRUNCATE TABLE public.push_subscriptions CASCADE;
TRUNCATE TABLE public.mess_plans CASCADE;
TRUNCATE TABLE public.mess_members CASCADE;
TRUNCATE TABLE public.mess_attendance CASCADE;
TRUNCATE TABLE public.mess_off_days CASCADE;
TRUNCATE TABLE public.mess_payments CASCADE;
TRUNCATE TABLE public.mess_one_time_meals CASCADE;
TRUNCATE TABLE public.mess_expenses CASCADE;
